### ISSUE TITLE
1.17

### ISSUE THREAD

**Issue by KyGost** [4o3F/Schwarz#1]
This mod is great!
Is there a 1.17 version planned?

**Comment by 4o3F** [comment]
@KyGost 
Done, but please help me test out this build
https://github.com/KaltsitMoe/Schwarz/releases/tag/2.0

**Comment by KyGost** [comment]
@KaltsitMoe 
Awesome, thank you very much!
Will try to test it tonight.

**Comment by KyGost** [comment]
Seems to be working.
I don't have a stable environment to compare, it feels like the numbers are a little more sensitive but they might not be.

As an aside; what *are* the units for the scores?

**Comment by 4o3F** [comment]
It's computed according to these two maps
[blockentity](https://github.com/KaltsitMoe/Schwarz/blob/main/src/main/java/moe/exusiai/schwarz/chunk/ChunkStatus.java#L27) and [mobs](https://github.com/KaltsitMoe/Schwarz/blob/main/src/main/java/moe/exusiai/schwarz/chunk/ChunkStatus.java#L42)
This may not be accurate, for example, chest if not connected with a hopper, cost almost no lag, but I'm unable to detect and filter them. So the mod may tell you that a storehouse is causing lag while it isn't

**Comment by KyGost** [comment]
Ohhh okay, and if optimisations are installed and whatnot that may also throw it off.

And any funky datapack stuff or anything else won't show.


Nonetheless it is quite useful! Thank you :-)

**Comment by 4o3F** [comment]
My pleasure
I'm closing this now
